import { validDrawPositions } from '../../../../validators/validDrawPositions';
import { getAllDrawMatchUps } from '../../../../drawEngine/getters/getMatchUps/drawMatchUps';
import tournamentEngine from '../../../../tournamentEngine/sync';
import { expect, it } from 'vitest';

// static examples (not generated by mocksEngine)
import tournament from './tournament.tods.json';
import { mutation } from './mutation.payload';

it('can recognize invalid matchUps', () => {
  let result = tournamentEngine.setState(tournament);
  expect(result.success).toEqual(true);
  result = tournamentEngine.allTournamentMatchUps();
  expect(result.matchUps).toEqual([]);

  result = validDrawPositions({ matchUps: result.matchUps });
  expect(result).toEqual(true);

  expect(mutation.tournamentId).toEqual(tournament.tournamentId);

  mutation.executionQueue.forEach((queueItem) => {
    const { method, params } = queueItem;
    const result = tournamentEngine[method](params);
    expect(result.success).toEqual(true);
  });

  const { drawDefinition } = mutation.executionQueue[0].params;
  const { matchUps: drawMatchUps } = getAllDrawMatchUps({
    inContext: true,
    drawDefinition,
  });
  result = validDrawPositions({ matchUps: drawMatchUps });
  expect(result).toEqual(true);

  const { matchUps: postExecutionMatchUps } =
    tournamentEngine.allTournamentMatchUps();

  result = validDrawPositions({
    matchUps: postExecutionMatchUps,
  });
  expect(result).toEqual(true);
});
