name: 'Setup pnpm'
description: 'Setup node, pnpm and install packages'
inputs:
  token:
    description: 'Token for npm package repository'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version

    - uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile --strict-peer-dependencies --ignore-scripts
