export enum EntryStatusEnum {
  CONFIRMED = 'CONFIRMED',
  DIRECT_ACCEPTANCE = 'DIRECT_ACCEPTANCE',
  ORGANISER_ACCEPTANCE = 'ORGANISER_ACCEPTANCE',
  REGISTERED = 'REGISTERED',

  ALTERNATE = 'ALTERNATE',
  WITHDRAWN = 'WITHDRAWN',

  SPECIAL_EXEMPT = 'SPECIAL_EXEMPT',
  JUNIOR_EXEMPT = 'JUNIOR_EXEMPT',

  // applies only to { participantType: INDIVIDUAL } entries in { eventType: DOUBLES }
  UNPAIRED = 'UNPAIRED', // legacy - being replaced by UNGROUPED
  UNGROUPED = 'UNGROUPED',

  // These entryStatus enums apply only to draw.entries
  LUCKY_LOSER = 'LUCKY_LOSER',
  FEED_IN = 'FEED_IN',
  QUALIFIER = 'QUALIFIER',
  WILDCARD = 'WILDCARD',
}

export const ALTERNATE = EntryStatusEnum.ALTERNATE;
export const CONFIRMED = EntryStatusEnum.CONFIRMED;
export const DIRECT_ACCEPTANCE = EntryStatusEnum.DIRECT_ACCEPTANCE;
export const FEED_IN = EntryStatusEnum.FEED_IN;
export const JUNIOR_EXEMPT = EntryStatusEnum.JUNIOR_EXEMPT;
export const LUCKY_LOSER = EntryStatusEnum.LUCKY_LOSER;
export const ORGANISER_ACCEPTANCE = EntryStatusEnum.ORGANISER_ACCEPTANCE;
export const QUALIFIER = EntryStatusEnum.QUALIFIER;
export const REGISTERED = EntryStatusEnum.REGISTERED;
export const SPECIAL_EXEMPT = EntryStatusEnum.SPECIAL_EXEMPT;
export const UNGROUPED = EntryStatusEnum.UNGROUPED;
export const UNPAIRED = EntryStatusEnum.UNPAIRED;
export const WILDCARD = EntryStatusEnum.WILDCARD;
export const WITHDRAWN = EntryStatusEnum.WITHDRAWN;

export const EQUIVALENT_ACCEPTANCE_STATUSES = [
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  JUNIOR_EXEMPT,
  ORGANISER_ACCEPTANCE,
  SPECIAL_EXEMPT,
];
export const DRAW_SPECIFIC_STATUSES = [
  FEED_IN,
  LUCKY_LOSER,
  QUALIFIER,
  WILDCARD,
];

export const DIRECT_ENTRY_STATUSES = [
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  FEED_IN,
  JUNIOR_EXEMPT,
  ORGANISER_ACCEPTANCE,
  SPECIAL_EXEMPT,
  WILDCARD,
];

export const STRUCTURE_SELECTED_STATUSES = [
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  FEED_IN,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  QUALIFIER,
  ORGANISER_ACCEPTANCE,
  SPECIAL_EXEMPT,
  WILDCARD,
];

export const VALID_ENTRY_STATUSES = [
  ALTERNATE,
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  FEED_IN,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  ORGANISER_ACCEPTANCE,
  QUALIFIER,
  REGISTERED,
  SPECIAL_EXEMPT,
  UNGROUPED,
  UNPAIRED,
  WILDCARD,
  WITHDRAWN,
];

// will be deprecated
export const STRUCTURE_ENTERED_TYPES = STRUCTURE_SELECTED_STATUSES;
export const VALID_ENTERED_TYPES = VALID_ENTRY_STATUSES;

export const entryStatusConstants = {
  ALTERNATE,
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  DRAW_SPECIFIC_STATUSES,
  EQUIVALENT_ACCEPTANCE_STATUSES,
  FEED_IN,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  ORGANISER_ACCEPTANCE,
  QUALIFIER,
  SPECIAL_EXEMPT,
  STRUCTURE_ENTERED_TYPES,
  STRUCTURE_SELECTED_STATUSES,
  UNGROUPED,
  UNPAIRED,
  VALID_ENTERED_TYPES,
  VALID_ENTRY_STATUSES,
  WILDCARD,
  WITHDRAWN,
};
