export const ALTERNATE = 'ALTERNATE';
export const CONFIRMED = 'CONFIRMED';
export const DIRECT_ACCEPTANCE = 'DIRECT_ACCEPTANCE';
export const FEED_IN = 'FEED_IN';
export const JUNIOR_EXEMPT = 'JUNIOR_EXEMPT';
export const LUCKY_LOSER = 'LUCKY_LOSER';
export const ORGANISER_ACCEPTANCE = 'ORGANISER_ACCEPTANCE';
export const QUALIFIER = 'QUALIFIER';
export const REGISTERED = 'REGISTERED';
export const SPECIAL_EXEMPT = 'SPECIAL_EXEMPT';
export const UNGROUPED = 'UNGROUPED';
export const UNPAIRED = 'UNPAIRED';
export const WILDCARD = 'WILDCARD';
export const WITHDRAWN = 'WITHDRAWN';

export const EQUIVALENT_ACCEPTANCE_STATUSES: any = [
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  JUNIOR_EXEMPT,
  ORGANISER_ACCEPTANCE,
  SPECIAL_EXEMPT,
];
export const DRAW_SPECIFIC_STATUSES: any = [FEED_IN, LUCKY_LOSER, QUALIFIER];

export const DIRECT_ENTRY_STATUSES: any = [
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  FEED_IN,
  JUNIOR_EXEMPT,
  ORGANISER_ACCEPTANCE,
  SPECIAL_EXEMPT,
  WILDCARD,
];

export const STRUCTURE_SELECTED_STATUSES: any = [
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  QUALIFIER,
  ORGANISER_ACCEPTANCE,
  SPECIAL_EXEMPT,
  WILDCARD,
];

export const VALID_ENTRY_STATUSES: any = [
  ALTERNATE,
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  FEED_IN,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  ORGANISER_ACCEPTANCE,
  QUALIFIER,
  REGISTERED,
  SPECIAL_EXEMPT,
  UNGROUPED,
  UNPAIRED,
  WILDCARD,
  WITHDRAWN,
];

export const entryStatusConstants: any = {
  ALTERNATE,
  CONFIRMED,
  DIRECT_ACCEPTANCE,
  DIRECT_ENTRY_STATUSES,
  DRAW_SPECIFIC_STATUSES,
  EQUIVALENT_ACCEPTANCE_STATUSES,
  FEED_IN,
  JUNIOR_EXEMPT,
  LUCKY_LOSER,
  ORGANISER_ACCEPTANCE,
  QUALIFIER,
  SPECIAL_EXEMPT,
  STRUCTURE_SELECTED_STATUSES,
  UNGROUPED,
  UNPAIRED,
  VALID_ENTRY_STATUSES,
  WILDCARD,
  WITHDRAWN,
};
