export const ALTERNATE = 'ALTERNATE';
export const FEED_IN = 'FEED_IN';
export const QUALIFIER = 'QUALIFIER';
export const WILDCARD = 'WILDCARD';
export const DIRECT_ACCEPTANCE = 'DIRECT_ACCEPTANCE';
export const CONFIRMED = 'CONFIRMED';
export const LUCKY_LOSER = 'LUCKY_LOSER';
export const ORGANISER_ACCEPTANCE = 'ORGANISER_ACCEPTANCE';
export const WITHDRAWN = 'WITHDRAWN';
export const UNPAIRED = 'UNPAIRED';

export const STRUCTURE_ENTERED_TYPES = [
  QUALIFIER,
  WILDCARD,
  DIRECT_ACCEPTANCE,
  CONFIRMED,
  LUCKY_LOSER,
  ORGANISER_ACCEPTANCE,
];

export const entryStatusConstants = {
  FEED_IN,
  WILDCARD,
  UNPAIRED,
  ALTERNATE,
  CONFIRMED,
  QUALIFIER,
  WITHDRAWN,
  LUCKY_LOSER,
  DIRECT_ACCEPTANCE,
  ORGANISER_ACCEPTANCE,

  STRUCTURE_ENTERED_TYPES,
};
