// Static map from mutation method names to their lock scope.
// Only mutation methods are mapped; query methods are never locked.
// Methods not in the map are not subject to lock checking.
// Lock management methods (addMutationLock, removeMutationLock) are deliberately excluded.

import { MutationLockScope } from '@Types/mutationLockTypes';

export const methodScopeMap: Record<string, MutationLockScope> = {
  // SCHEDULING — scheduleGovernor/mutate
  setMatchUpHomeParticipantId: 'SCHEDULING',
  calculateScheduleTimes: 'SCHEDULING',
  addMatchUpScheduledDate: 'SCHEDULING',
  bulkScheduleTournamentMatchUps: 'SCHEDULING',
  toggleParticipantCheckInState: 'SCHEDULING',
  removeMatchUpCourtAssignment: 'SCHEDULING',
  proAutoSchedule: 'SCHEDULING',
  bulkUpdateCourtAssignments: 'SCHEDULING',
  allocateTeamMatchUpCourts: 'SCHEDULING',
  scheduleMatchUps: 'SCHEDULING',
  addSchedulingProfileRound: 'SCHEDULING',
  proConflicts: 'SCHEDULING',
  reorderUpcomingMatchUps: 'SCHEDULING',
  generateVirtualCourts: 'SCHEDULING',
  bulkRescheduleMatchUps: 'SCHEDULING',
  clearScheduledMatchUps: 'SCHEDULING',
  matchUpScheduleChange: 'SCHEDULING',
  bulkScheduleMatchUps: 'SCHEDULING',
  scheduleProfileRounds: 'SCHEDULING',
  clearMatchUpSchedule: 'SCHEDULING',
  addMatchUpScheduledTime: 'SCHEDULING',
  setMatchUpDailyLimits: 'SCHEDULING',
  assignMatchUpCourt: 'SCHEDULING',
  assignMatchUpVenue: 'SCHEDULING',
  generateBookings: 'SCHEDULING',
  validateSchedulingProfile: 'SCHEDULING',
  setSchedulingProfile: 'SCHEDULING',
  addCourtGridBooking: 'SCHEDULING',
  removeCourtGridBooking: 'SCHEDULING',
  addMatchUpCourtOrder: 'SCHEDULING',
  addMatchUpStartTime: 'SCHEDULING',
  addMatchUpEndTime: 'SCHEDULING',
  addMatchUpStopTime: 'SCHEDULING',
  addMatchUpResumeTime: 'SCHEDULING',
  addMatchUpOfficial: 'SCHEDULING',
  addMatchUpScheduleItems: 'SCHEDULING',

  // DRAWS — drawsGovernor/mutate
  setDrawParticipantRepresentativeIds: 'DRAWS',
  resetVoluntaryConsolationStructure: 'DRAWS',
  withdrawParticipantAtDrawPosition: 'DRAWS',
  addVoluntaryConsolationStructure: 'DRAWS',
  luckyLoserDrawPositionAssignment: 'DRAWS',
  shiftAdHocRounds: 'DRAWS',
  setPositionAssignments: 'DRAWS',
  swapAdHocRounds: 'DRAWS',
  alternateDrawPositionAssignment: 'DRAWS',
  removeDrawPositionAssignment: 'DRAWS',
  automatedPlayoffPositioning: 'DRAWS',
  modifySeedAssignment: 'DRAWS',
  qualifierDrawPositionAssignment: 'DRAWS',
  qualifierProgression: 'DRAWS',
  setStructureOrder: 'DRAWS',
  attachQualifyingStructure: 'DRAWS',
  renameStructures: 'DRAWS',
  assignDrawPositionBye: 'DRAWS',
  addDrawDefinitionTimeItem: 'DRAWS',
  removeStructure: 'DRAWS',
  addVoluntaryConsolationStage: 'DRAWS',
  resetQualifyingStructure: 'DRAWS',
  swapDrawPositionAssignments: 'DRAWS',
  removeSeededParticipant: 'DRAWS',
  addQualifyingStructure: 'DRAWS',
  adHocPositionSwap: 'DRAWS',
  addPlayoffStructures: 'DRAWS',
  automatedPositioning: 'DRAWS',
  modifyDrawDefinition: 'DRAWS',
  resetDrawDefinition: 'DRAWS',
  pruneDrawDefinition: 'DRAWS',
  assignDrawPosition: 'DRAWS',
  deleteAdHocMatchUps: 'DRAWS',
  removeRoundMatchUps: 'DRAWS',
  updateTeamLineUp: 'DRAWS',
  addAdHocMatchUps: 'DRAWS',
  modifyDrawName: 'DRAWS',
  setSubOrder: 'DRAWS',
  attachConsolationStructures: 'DRAWS',
  attachPlayoffStructures: 'DRAWS',
  attachStructures: 'DRAWS',
  // drawsGovernor/generate
  generateDrawTypeAndModifyDrawDefinition: 'DRAWS',
  generateAndPopulatePlayoffStructures: 'DRAWS',
  generateDrawMaticRound: 'DRAWS',
  generateVoluntaryConsolation: 'DRAWS',
  generateDrawDefinition: 'DRAWS',
  generateQualifyingStructure: 'DRAWS',
  generateDrawStructuresAndLinks: 'DRAWS',
  generateAdHocMatchUps: 'DRAWS',
  generateAdHocRounds: 'DRAWS',
  drawMatic: 'DRAWS',
  addFinishingRounds: 'DRAWS',
  buildDrawHierarchy: 'DRAWS',
  autoSeeding: 'DRAWS',

  // SCORING — matchUpGovernor/mutate (scoring-related)
  setMatchUpStatus: 'SCORING',
  setMatchUpState: 'SCORING',
  bulkMatchUpStatusUpdate: 'SCORING',
  setDelegatedOutcome: 'SCORING',
  removeDelegatedOutcome: 'SCORING',
  updateTieMatchUpScore: 'SCORING',
  resetScorecard: 'SCORING',
  setOrderOfFinish: 'SCORING',
  resetAdHocMatchUps: 'SCORING',
  applyLineUps: 'SCORING',
  resetTieFormat: 'SCORING',
  enableTieAutoCalc: 'SCORING',
  disableTieAutoCalc: 'SCORING',
  resetMatchUpLineUps: 'SCORING',

  // MATCHUPS — matchUpGovernor/mutate (participant assignment)
  assignMatchUpSideParticipant: 'MATCHUPS',
  replaceTieMatchUpParticipantId: 'MATCHUPS',
  assignTieMatchUpParticipantId: 'MATCHUPS',
  removeTieMatchUpParticipantId: 'MATCHUPS',
  removeMatchUpSideParticipant: 'MATCHUPS',
  substituteParticipant: 'MATCHUPS',
  checkOutParticipant: 'MATCHUPS',
  checkInParticipant: 'MATCHUPS',
  setMatchUpFormat: 'MATCHUPS',

  // SCORING — scoreGovernor/mutate
  createMatchUp: 'SCORING',
  addPoint: 'SCORING',
  resolvePointValue: 'SCORING',
  calculatePointsTo: 'SCORING',
  inferServeSide: 'SCORING',

  // PARTICIPANTS — participantGovernor/mutate
  modifyPersonRequests: 'PARTICIPANTS',
  removePersonRequests: 'PARTICIPANTS',
  addPersonRequests: 'PARTICIPANTS',
  setParticipantScaleItems: 'PARTICIPANTS',
  setParticipantScaleItem: 'PARTICIPANTS',
  modifyIndividualParticipantIds: 'PARTICIPANTS',
  createTeamsFromParticipantAttributes: 'PARTICIPANTS',
  modifyParticipantsSignInStatus: 'PARTICIPANTS',
  addIndividualParticipantIds: 'PARTICIPANTS',
  modifyParticipantOtherName: 'PARTICIPANTS',
  regenerateParticipantNames: 'PARTICIPANTS',
  addDynamicRatings: 'PARTICIPANTS',
  createGroupParticipant: 'PARTICIPANTS',
  modifyParticipantName: 'PARTICIPANTS',
  scaledTeamAssignment: 'PARTICIPANTS',
  removeRatings: 'PARTICIPANTS',
  removePenalty: 'PARTICIPANTS',
  modifyPenalty: 'PARTICIPANTS',
  deleteParticipants: 'PARTICIPANTS',
  mergeParticipants: 'PARTICIPANTS',
  modifyParticipant: 'PARTICIPANTS',
  addParticipants: 'PARTICIPANTS',
  addPenalty: 'PARTICIPANTS',
  addParticipant: 'PARTICIPANTS',
  addPersons: 'PARTICIPANTS',
  removeIndividualParticipantIds: 'PARTICIPANTS',
  removeParticipantIdsFromAllTeams: 'PARTICIPANTS',

  // ENTRIES — entriesGovernor/mutate
  destroyPairEntries: 'ENTRIES',
  destroyPairEntry: 'ENTRIES',
  setEntryPosition: 'ENTRIES',
  setEntryPositions: 'ENTRIES',
  promoteAlternate: 'ENTRIES',
  promoteAlternates: 'ENTRIES',
  removeDrawEntries: 'ENTRIES',
  modifyEntriesStatus: 'ENTRIES',
  addEventEntryPairs: 'ENTRIES',
  removeEventEntries: 'ENTRIES',
  modifyEventEntries: 'ENTRIES',
  addDrawEntries: 'ENTRIES',
  addEventEntries: 'ENTRIES',

  // EVENTS — eventGovernor/mutate
  deleteFlightProfileAndFlightDraws: 'EVENTS',
  modifyEventMatchUpFormatTiming: 'EVENTS',
  removeEventMatchUpFormatTiming: 'EVENTS',
  setEventDates: 'EVENTS',
  setEventEndDate: 'EVENTS',
  setEventStartDate: 'EVENTS',
  deleteFlightAndFlightDraw: 'EVENTS',
  refreshEventDrawOrder: 'EVENTS',
  modifyPairAssignment: 'EVENTS',
  updateDrawIdsOrder: 'EVENTS',
  addDrawDefinition: 'EVENTS',
  deleteDrawDefinitions: 'EVENTS',
  assignSeedPositions: 'EVENTS',
  attachFlightProfile: 'EVENTS',
  removeScaleValues: 'EVENTS',
  setEventDisplay: 'EVENTS',
  validateCategory: 'EVENTS',
  removeSeeding: 'EVENTS',
  deleteEvents: 'EVENTS',
  modifyEvent: 'EVENTS',
  addFlight: 'EVENTS',
  addEvent: 'EVENTS',
  // eventGovernor/generate
  generateEventsFromTieFormat: 'EVENTS',

  // VENUES — venueGovernor/mutate
  modifyCourtAvailability: 'VENUES',
  deleteVenue: 'VENUES',
  deleteVenues: 'VENUES',
  addCourt: 'VENUES',
  addCourts: 'VENUES',
  disableCourts: 'VENUES',
  disableVenues: 'VENUES',
  enableCourts: 'VENUES',
  enableVenues: 'VENUES',
  deleteCourt: 'VENUES',
  modifyCourt: 'VENUES',
  modifyVenue: 'VENUES',
  addVenue: 'VENUES',

  // PUBLISHING — publishingGovernor/mutate
  publishEventSeeding: 'PUBLISHING',
  unPublishEventSeeding: 'PUBLISHING',
  unPublishParticipants: 'PUBLISHING',
  unPublishOrderOfPlay: 'PUBLISHING',
  publishParticipants: 'PUBLISHING',
  publishOrderOfPlay: 'PUBLISHING',
  unPublishEvent: 'PUBLISHING',
  publishEvent: 'PUBLISHING',

  // TOURNAMENT — tournamentGovernor/mutate
  setTournamentStatus: 'TOURNAMENT',
  setTournamentName: 'TOURNAMENT',
  setTournamentNotes: 'TOURNAMENT',
  setTournamentCategories: 'TOURNAMENT',
  setTournamentDates: 'TOURNAMENT',
  setTournamentEndDate: 'TOURNAMENT',
  setTournamentStartDate: 'TOURNAMENT',
  addTournamentExtension: 'TOURNAMENT',
  removeTournamentExtension: 'TOURNAMENT',

  // TIE_FORMAT — tieFormatGovernor/mutate
  modifyCollectionDefinition: 'TIE_FORMAT',
  removeCollectionGroup: 'TIE_FORMAT',
  orderCollectionDefinitions: 'TIE_FORMAT',
  removeCollectionDefinition: 'TIE_FORMAT',
  addCollectionGroup: 'TIE_FORMAT',
  addCollectionDefinition: 'TIE_FORMAT',
  modifyTieFormat: 'TIE_FORMAT',
  aggregateTieFormats: 'TIE_FORMAT',

  // POLICY — policyGovernor/mutate
  attachPolicies: 'POLICY',
  removePolicy: 'POLICY',

  // COMPETITION — competitionGovernor/mutate
  linkTournaments: 'COMPETITION',
  unlinkTournament: 'COMPETITION',
  unlinkTournaments: 'COMPETITION',

  // RANKING — rankingGovernor/mutate
  applyTournamentRankingPoints: 'RANKING',
};
