export const COLLEGE_DEFAULT = 'COLLEGE_DEFAULT';
export const COLLEGE_JUCO = 'COLLEGE_JUCO';
export const COLLEGE_D3 = 'COLLEGE_D3';
export const DOMINANT_DUO = 'DOMINANT_DUO';
export const DOMINANT_DUO_MIXED = 'DOMINANT_DUO_MIXED';
export const LAVER_CUP = 'LAVER_CUP';
export const TEAM_DOUBLES_3_AGGREGATION = 'TEAM_DOUBLES_3_AGGREGATION';
export const TIME_TENNIS = 'TIME_TENNIS';
export const USTA_BREWER_CUP = 'USTA_BREWER_CUP';
export const USTA_OZAKI_CUP = 'USTA_OZAKI_CUP';
export const USTA_COLLEGE = 'USTA_COLLEGE';
export const USTA_GOLD_TEAM_CHALLENGE = 'USTA_GOLD_TEAM_CHALLENGE';
export const USTA_LEVEL_1 = 'USTA_LEVEL_1';
export const USTA_INTERSECTIONAL = 'USTA_INTERSECTIONAL';
export const USTA_SECTION_BATTLE = 'USTA_SECTION_BATTLE';
export const USTA_SOUTHERN_LEVEL_5 = 'USTA_SOUTHERN_LEVEL_5';
export const USTA_TOC = 'USTA_TOC';
export const USTA_WTT_ITT = 'USTA_WTT_ITT';
export const USTA_ZONAL = 'USTA_ZONAL';

export const tieFormatConstants = {
  COLLEGE_D3,
  COLLEGE_DEFAULT,
  COLLEGE_JUCO,
  DOMINANT_DUO,
  DOMINANT_DUO_MIXED,
  LAVER_CUP,
  TEAM_DOUBLES_3_AGGREGATION,
  TIME_TENNIS,
  USTA_BREWER_CUP,
  USTA_OZAKI_CUP,
  USTA_COLLEGE,
  USTA_GOLD_TEAM_CHALLENGE,
  USTA_INTERSECTIONAL,
  USTA_LEVEL_1,
  USTA_SECTION_BATTLE,
  USTA_SOUTHERN_LEVEL_5,
  USTA_TOC,
  USTA_WTT_ITT,
  USTA_ZONAL,
};

export default tieFormatConstants;
