import { validDrawPositions } from '@Validators/validDrawPositions';
import { getAllDrawMatchUps } from '@Query/matchUps/drawMatchUps';
import tournamentEngine from '../engines/syncEngine';
import queryEngine from '../engines/queryEngine';
import { expect, it } from 'vitest';

// static examples (not generated by mocksEngine)
import tournament from '../queries/matchUps/checkValidMatchUps/tournament.tods.json';
import { mutation } from '../queries/matchUps/checkValidMatchUps/mutation.payload';

it('can recognize invalid matchUps', () => {
  let result = tournamentEngine.setState(tournament);
  expect(result.success).toEqual(true);
  result = queryEngine.allTournamentMatchUps();
  expect(result.matchUps).toEqual([]);

  result = validDrawPositions({ matchUps: result.matchUps });
  expect(result).toEqual(true);

  expect(mutation.tournamentId).toEqual(tournament.tournamentId);

  mutation.executionQueue.forEach((queueItem) => {
    const { method, params } = queueItem;
    const result = tournamentEngine[method](params);
    expect(result.success).toEqual(true);
  });

  const { drawDefinition } = mutation.executionQueue[0].params;
  const { matchUps: drawMatchUps } = getAllDrawMatchUps({
    inContext: true,
    drawDefinition,
  });
  result = validDrawPositions({ matchUps: drawMatchUps });
  expect(result).toEqual(true);

  const { matchUps: postExecutionMatchUps } = queryEngine.allTournamentMatchUps();

  result = validDrawPositions({
    matchUps: postExecutionMatchUps,
  });
  expect(result).toEqual(true);
});
