import { getAllDrawMatchUps } from '../../getters/getMatchUps/drawMatchUps';
import { modifyDrawNotice } from '../../notifications/drawNotifications';
import { directParticipants } from '../matchUpGovernor/directParticipants';
import { getAvailablePlayoffRounds } from './getAvailablePlayoffRounds';
import { matchUpIsComplete } from '../scoreGovernor/matchUpIsComplete';
import { positionTargets } from '../positionGovernor/positionTargets';
import { getMatchUpId } from '../../../global/functions/extractors';
import { generateTieMatchUps } from '../../generators/tieMatchUps';
import { playoff } from '../../generators/playoffStructures';
import { findStructure } from '../../getters/findStructure';
import { addGoesTo } from '../matchUpGovernor/addGoesTo';
import { getSourceRounds } from './getSourceRounds';

import { INVALID_VALUES } from '../../../constants/errorConditionConstants';
import { SUCCESS } from '../../../constants/resultConstants';
import { TEAM } from '../../../constants/matchUpTypes';
import {
  LOSER,
  PLAY_OFF,
  TOP_DOWN,
} from '../../../constants/drawDefinitionConstants';

/**
 *
 * @param {object} drawDefinition - passed in automatically by drawEngine
 * @param {string} structureId - id of structure to which playoff structures are to be added
 * @param {number[]} roundNumbers - source roundNumbers which will feed target structures, e.g. [1, 2]
 * @param {object[]} roundProfiles - source roundNumbers as Object.keys with depth as Object.values, e.g. [{ 1: 2}, {2: 1}]
 * @param {number[]} playoffPositions - positions to be played off
 * @param {boolean} exitProfileLimit - limit playoff rounds generated by the attributes present in playoffAttributes
 * @param {object} playoffAttributes - mapping of exitProfile to structure names, e.g. 0-1-1 for SOUTH
 * @param {string} playoffStructureNameBase - Root word for default playoff naming, e.g. 'Playoff' for 'Playoff 3-4'
 *
 */
export function addPlayoffStructures(params) {
  const {
    playoffRoundsRanges: availablePlayoffRoundsRanges,
    playoffRounds: availablePlayoffRounds,
    error: playoffRoundsError,
  } = getAvailablePlayoffRounds(params);
  if (playoffRoundsError) return { error: playoffRoundsError };

  const {
    playoffSourceRounds,
    playoffRoundsRanges,
    playoffPositionsReturned,
    error: sourceRoundsError,
  } = getSourceRounds(params);
  if (sourceRoundsError) return { error: sourceRoundsError };

  const {
    structureId: sourceStructureId,
    addNameBaseToAttributeName,
    playoffStructureNameBase,
    playoffAttributes,
    playoffPositions,
    exitProfileLimit,
    drawDefinition,
    roundProfiles,
    roundNumbers,
    idPrefix,
    isMock,
    event,
    uuids,
  } = params;

  const roundProfile =
    roundProfiles?.length && Object.assign({}, ...roundProfiles);

  const targetRoundNumbers =
    roundNumbers ||
    (typeof roundProfiles === 'object' &&
      roundProfiles.map((p) => Object.keys(p)).flat());

  const validRoundNumbers =
    targetRoundNumbers &&
    targetRoundNumbers.map((p) => !isNaN(p) && parseInt(p)).filter(Boolean);

  if (validRoundNumbers) {
    if (!Array.isArray(validRoundNumbers))
      return { error: INVALID_VALUES, validRoundNumbers };

    validRoundNumbers.forEach((roundNumber) => {
      if (!availablePlayoffRounds.includes(roundNumber))
        return { error: INVALID_VALUES, roundNumber };
    });
  }

  if (playoffPositions) {
    playoffPositions.forEach((playoffPosition) => {
      if (!playoffPositionsReturned.includes(playoffPosition))
        return { error: INVALID_VALUES, playoffPosition };
    });
  }

  const { structure } = findStructure({
    structureId: sourceStructureId,
    drawDefinition,
  });

  const sourceRounds = validRoundNumbers || playoffSourceRounds;
  const roundsRanges = validRoundNumbers
    ? availablePlayoffRoundsRanges
    : playoffRoundsRanges;

  const newLinks = [];
  const newStructureIds = [];

  for (const roundNumber of sourceRounds) {
    const roundInfo = roundsRanges.find(
      (roundInfo) => roundInfo.roundNumber === roundNumber
    );
    if (!roundInfo) return { error: INVALID_VALUES, message: { roundNumber } };
    const drawSize = roundInfo.finishingPositions.length;
    const finishingPositionOffset =
      Math.min(...roundInfo.finishingPositions) - 1;

    const stageSequence = 2;
    const sequenceLimit =
      roundProfile &&
      roundProfile[roundNumber] &&
      stageSequence + roundProfile[roundNumber] - 1;

    const result = playoff({
      exitProfile: `0-${roundNumber}`,
      addNameBaseToAttributeName,
      playoffStructureNameBase,
      finishingPositionOffset,
      playoffAttributes,
      exitProfileLimit,
      stage: PLAY_OFF,
      drawDefinition,
      roundOffset: 0,
      sequenceLimit,
      stageSequence,
      drawSize,
      idPrefix,
      isMock,
      uuids,
    });
    if (result.error) return result;

    if (result.structure) {
      newStructureIds.push(result.structure.structureId);
      const link = {
        linkType: LOSER,
        source: {
          structureId: sourceStructureId,
          roundNumber,
        },
        target: {
          structureId: result.structure.structureId,
          feedProfile: TOP_DOWN,
          roundNumber: 1,
        },
      };

      newLinks.push(link);
    }
  }

  if (!newStructureIds.length) return { error: INVALID_VALUES };

  drawDefinition.links = (drawDefinition.links || []).concat(...newLinks);

  const { matchUps: inContextDrawMatchUps, matchUpsMap } = getAllDrawMatchUps({
    includeByeMatchUps: true,
    inContext: true,
    drawDefinition,
  });

  const addedMatchUpIds = inContextDrawMatchUps
    .filter(({ structureId }) => newStructureIds.includes(structureId))
    .map(getMatchUpId);

  const addedMatchUps = matchUpsMap?.drawMatchUps?.filter(({ matchUpId }) =>
    addedMatchUpIds.includes(matchUpId)
  );

  if (addedMatchUps.length) {
    const tieFormat = drawDefinition.tieFormat || event?.tieFormat || undefined;

    if (tieFormat) {
      addedMatchUps.forEach((matchUp) => {
        const { tieMatchUps } = generateTieMatchUps({ tieFormat, isMock });
        Object.assign(matchUp, { tieMatchUps, matchUpType: TEAM });
      });
    }
  }

  // now advance any players from completed matchUps into the newly added structures
  const completedMatchUps = inContextDrawMatchUps.filter(
    (matchUp) =>
      matchUpIsComplete(matchUp) && matchUp.structureId === sourceStructureId
  );

  completedMatchUps.forEach((matchUp) => {
    const { matchUpId, score, winningSide } = matchUp;
    const targetData = positionTargets({
      inContextDrawMatchUps,
      drawDefinition,
      matchUpId,
      structure,
    });
    const result = directParticipants({
      inContextDrawMatchUps,
      drawDefinition,
      matchUpsMap,
      winningSide,
      targetData,
      matchUpId,
      structure,
      matchUp,
      score,
    });
    if (result.error) console.log(result.error);
  });

  if (params.goesTo)
    addGoesTo({
      inContextDrawMatchUps,
      drawDefinition,
      matchUpsMap,
    });

  modifyDrawNotice({ drawDefinition, structureIds: newStructureIds });

  return { ...SUCCESS };
}
