export { destroyPairEntries, destroyPairEntry } from '@Mutate/entries/destroyPairEntry';
export { setEntryPosition, setEntryPositions } from '@Mutate/entries/setEntryPositions';
export { promoteAlternate, promoteAlternates } from '@Mutate/entries/promoteAlternate';
export { removeDrawEntries } from '@Mutate/drawDefinitions/removeDrawEntries';
export { modifyEntriesStatus } from '@Mutate/entries/modifyEntriesStatus';
export { addEventEntryPairs } from '@Mutate/entries/addEventEntryPairs';
export { removeEventEntries } from '@Mutate/entries/removeEventEntries';
export { modifyEventEntries } from '@Mutate/entries/modifyEventEntries';
export { addDrawEntries } from '@Mutate/drawDefinitions/addDrawEntries';
export { addEventEntries } from '@Mutate/entries/addEventEntries';
