module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Competition Factory',
      items: [
        'introduction',
        'data-standards',
        'time-capsule',
        {
          'TMX Example': [
            'tmx',
            'tmx/overview',
            'tmx/participants',
            'tmx/events-categories',
            'tmx/draws',
            'tmx/matchups',
            'tmx/venues-scheduling',
            'tmx/browser-console',
            'tmx/factory-server',
          ],
        },
        'installation',
        'acknowledgements',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          Participants: ['concepts/participants', 'concepts/participant-context', 'concepts/scaleItems'],
        },
        {
          Policies: [
            'concepts/policies',
            'policies/roundRobinTallyPolicy',
            'policies/avoidance',
            'policies/positionActions',
            'policies/matchUpActions',
            'policies/roundNaming',
            'policies/participantPolicy',
            'policies/seedingPolicy',
            'policies/feedInPolicy',
            'policies/scheduling',
            'policies/scoringPolicy',
            'policies/draws',
            // 'policies/rankingPolicy',
            'policies/progressionPolicy',
            'policies/consolationPolicy',
            'policies/competitiveBands',
          ],
        },
        {
          Events: [
            'concepts/events/events-overview',
            'concepts/events/categories',
            'concepts/events/entries',
            'concepts/events/flights',
          ],
        },
        {
          Draws: ['concepts/draws-overview', 'concepts/draw-types', 'concepts/actions'],
        },
        {
          matchUps: [
            'concepts/matchup-overview',
            'concepts/matchup-context',
            'concepts/matchup-filtering',
            'concepts/tieMatchUp',
            'concepts/lineUp',
            'concepts/tieFormat',
          ],
        },
        {
          Scheduling: [
            'concepts/scheduling-overview',
            'concepts/venues-courts',
            'concepts/scheduling-policy',
            'concepts/scheduling-profile',
            'concepts/automated-scheduling',
            'concepts/pro-scheduling',
            'concepts/scheduling-conflicts',
          ],
        },
        'concepts/publishing',
      ],
    },
    {
      type: 'category',
      label: 'State Engines',
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'engines/state-engines',
        },
        'engines/engine-methods',
        'engines/engine-logging',
        'engines/engine-middleware',
        'engines/mutation-engines',
        'engines/subscriptions',
        'engines/custom-engines',
        'engines/global-state',
        {
          type: 'category',
          label: 'Scoring Engine',
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'scoring-engine/scoring-engine-overview',
            },
            'scoring-engine/scoring-engine-api',
            'scoring-engine/event-handlers',
            'scoring-engine/format-support',
            'scoring-engine/visualization-applications',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Governors',
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'governors/governors-overview',
        },
        'governors/competition-governor',
        'governors/draws-governor',
        'governors/entries-governor',
        'governors/event-governor',
        'governors/generation-governor',
        'governors/matchup-governor',
        'governors/matchup-format-governor',
        'governors/mocks-governor',
        'governors/participant-governor',
        'governors/policy-governor',
        'governors/publishing-governor',
        'governors/query-governor',
        'governors/report-governor',
        'governors/schedule-governor',
        'governors/score-governor',
        'governors/tournament-governor',
        'governors/venue-governor',
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'tools/tools-overview',
        },
        'tools/make-deep-copy',
        'tools/structure-sort',
        'tools/json-to-csv',
        'tools/tools-api',
      ],
    },
    {
      Testing: [
        { type: 'doc', label: 'Overview', id: 'testing/testing-overview' },
        {
          type: 'category',
          label: 'mocksEngine',
          collapsed: false,
          items: [
            'testing/mocks-engine-overview',
            'testing/mocks-engine-getting-started',
            'testing/mocks-engine-tournament-generation',
            'testing/mocks-engine-participants',
            'testing/mocks-engine-outcomes',
            'testing/mocks-engine-patterns',
          ],
        },
        'testing/factory-server',
      ],
    },
    {
      type: 'category',
      label: 'Data',
      items: [
        'constants',
        {
          Codes: ['codes/age-category', 'codes/matchup-format'],
        },
        'types/typedefs',
        'concepts/accessors',
        'concepts/timeItems',
        'concepts/extensions',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      items: ['migration'],
    },
  ],
};
