export const mutation = {
  tournamentId: '36EA9520-9153-4487-8574-D0472DDD1C32',
  timestamp: 1607691116152,
  executionQueue: [
    {
      method: 'addDrawDefinition',
      params: {
        eventId: 'DAEA5763-8A83-417C-AAC9-6F2C0A53E901',
        drawDefinition: {
          drawId: '31ffccbb-be42-4f57-8b98-cf89e96adaaa',
          drawName: 'ELIMINATION',
          drawProfile: {
            drawType: 'ELIMINATION',
            drawSize: 32,
            automated: 'automated',
            seedsCount: 8,
            structureOptions: {
              groupSize: '',
            },
            category: {
              ageCategoryCode: 'U18',
              type: 'AGE',
              subType: 'JUNIOR',
              createdAt: '2020-12-11T12:51:56.141Z',
              updatedAt: '2020-12-11T12:51:56.141Z',
            },
            matchUpFormat: 'SET3-S:6/TB7',
          },
          entryProfile: {
            QUALIFYING: {
              drawSize: null,
              sequenceMap: null,
              alternates: true,
              wildcardsCount: null,
            },
            MAIN: {
              drawSize: 32,
              qualifiersCount: null,
              alternates: true,
              wildcardsCount: null,
            },
          },
          entries: [
            {
              participantId: '69D53E88-8921-4135-BE08-7D3955E9D905',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'DFF8511C-92D3-4B83-8FA6-13CA49AF8B0E',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'EEC077F9-9F34-40AE-ABBB-6FD680B7EA60',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'D5512670-C0F6-424D-B012-218E9C2B6A01',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: '6B716DFF-D553-4AC3-B0AF-12BEF8B1F56C',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'ECD2C517-E82B-415F-A689-C7245689274A',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: '38524857-02A0-47C2-8511-A63CCD3EB444',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'BD2E3868-36C8-43D1-A06F-D6A953B512B9',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'E293007D-40B5-43F3-B4E3-9FD397A5E3E7',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: '3DA2502B-85CC-42F7-902F-5CDDCB29EBB7',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: '5036DEBC-230D-4EBE-9C31-41B556E8951C',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'F553D401-2F62-4AFF-892B-0C189671FC1C',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'DE072B76-F386-48BC-8408-F9301CA8DB88',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'C8222AA6-13AC-4152-A1E2-929CA0FDA46D',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: 'CF68FD6D-B973-4F59-9818-020D05FB3F65',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: '1DDC2CD1-CD63-4C43-AA0F-767D77F7F5B7',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: '5BBABB87-11FD-47F6-941E-84AB3A76DEAF',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: '95BA08D4-F49B-4F23-A111-48CF09D0D886',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: '1EED4E97-AD8A-4E89-BF11-B2D89E41105D',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
            {
              participantId: '3DE351D7-3839-4382-9C3E-A362588373BC',
              entryStage: 'MAIN',
              entryStatus: 'DIRECT_ACCEPTANCE',
            },
          ],
          links: [],
          structures: [
            {
              structureName: 'MAIN',
              stageSequence: 1,
              finishingPosition: 'ROUND_OUTCOME',
              seedAssignments: [
                {
                  seedNumber: 1,
                  seedValue: 1,
                },
                {
                  seedNumber: 2,
                  seedValue: 2,
                },
                {
                  seedNumber: 3,
                  seedValue: 3,
                },
                {
                  seedNumber: 4,
                  seedValue: 4,
                },
                {
                  seedNumber: 5,
                  seedValue: 5,
                },
                {
                  seedNumber: 6,
                  seedValue: 6,
                },
                {
                  seedNumber: 7,
                  seedValue: 7,
                },
                {
                  seedNumber: 8,
                  seedValue: 8,
                },
              ],
              structureId: '24fe0a92-e7c1-423c-a296-ca9f5fe4ae8c',
              stage: 'MAIN',
              matchUps: [
                {
                  matchUpId: 'ab02c176-1b4c-4ad1-9c3b-a469eceee8ce',
                  roundNumber: 1,
                  roundPosition: 1,
                  matchUpStatus: 'BYE',
                  drawPositions: [1, 2],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: '88812a63-82cc-4dec-b0a1-59579db1ed75',
                  roundNumber: 1,
                  roundPosition: 2,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [3, 4],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                },
                {
                  matchUpId: 'e5c793d1-03c7-4525-84d6-d3f6fce15b2d',
                  roundNumber: 1,
                  roundPosition: 3,
                  matchUpStatus: 'BYE',
                  drawPositions: [5, 6],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: '3c1e4dc5-ba8b-4a35-97d6-b69bbbaaeef0',
                  roundNumber: 1,
                  roundPosition: 4,
                  matchUpStatus: 'BYE',
                  drawPositions: [7, 8],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: 'adb9abbd-7935-46f0-8e93-14ea718134a3',
                  roundNumber: 1,
                  roundPosition: 5,
                  matchUpStatus: 'BYE',
                  drawPositions: [9, 10],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: 'd694af22-c8f7-4465-abb2-79714490f536',
                  roundNumber: 1,
                  roundPosition: 6,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [11, 12],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                },
                {
                  matchUpId: '5326ab6d-45ee-4179-b96f-12892e6d1967',
                  roundNumber: 1,
                  roundPosition: 7,
                  matchUpStatus: 'BYE',
                  drawPositions: [13, 14],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: 'f1e3b216-36ab-47ea-8da1-5c3ad05a8bb8',
                  roundNumber: 1,
                  roundPosition: 8,
                  matchUpStatus: 'BYE',
                  drawPositions: [15, 16],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: '42b86ca3-2dd0-490d-b92f-99720d5a6c79',
                  roundNumber: 1,
                  roundPosition: 9,
                  matchUpStatus: 'BYE',
                  drawPositions: [17, 18],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: '81e5d4ca-112d-4d3b-b9d9-876c8f750b90',
                  roundNumber: 1,
                  roundPosition: 10,
                  matchUpStatus: 'BYE',
                  drawPositions: [19, 20],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: 'a24aeaad-24e7-4faf-946b-0b88f7c5b9db',
                  roundNumber: 1,
                  roundPosition: 11,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [21, 22],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                },
                {
                  matchUpId: 'dda21e3d-afe1-4a31-94de-152610f4761f',
                  roundNumber: 1,
                  roundPosition: 12,
                  matchUpStatus: 'BYE',
                  drawPositions: [23, 24],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: '970f41f5-da7d-4c07-9d57-f53cb59e0f2b',
                  roundNumber: 1,
                  roundPosition: 13,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [25, 26],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                },
                {
                  matchUpId: '3504924e-2a2e-4070-b8d8-26626175c6a3',
                  roundNumber: 1,
                  roundPosition: 14,
                  matchUpStatus: 'BYE',
                  drawPositions: [27, 28],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: '2764acd5-d657-4e9d-8ef1-efaf7c100e0c',
                  roundNumber: 1,
                  roundPosition: 15,
                  matchUpStatus: 'BYE',
                  drawPositions: [29, 30],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: '112b502b-9aeb-4cea-a7f8-5892463d04db',
                  roundNumber: 1,
                  roundPosition: 16,
                  matchUpStatus: 'BYE',
                  drawPositions: [31, 32],
                  finishingRound: 5,
                  finishingPositionRange: {
                    loser: [17, 32],
                    winner: [1, 16],
                  },
                  matchUpStatusCodes: [],
                },
                {
                  matchUpId: '1a720644-9b7c-4cd1-a7ad-972647811454',
                  roundNumber: 2,
                  roundPosition: 1,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [1, null],
                  finishingRound: 4,
                  finishingPositionRange: {
                    loser: [9, 16],
                    winner: [1, 8],
                  },
                },
                {
                  matchUpId: '5d5a995d-f8e2-4b75-bf98-111786940a21',
                  roundNumber: 2,
                  roundPosition: 2,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [5, 7],
                  finishingRound: 4,
                  finishingPositionRange: {
                    loser: [9, 16],
                    winner: [1, 8],
                  },
                },
                {
                  matchUpId: 'd2d19fdf-2113-406e-bab6-5ecc7c9e449c',
                  roundNumber: 2,
                  roundPosition: 3,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [9, null],
                  finishingRound: 4,
                  finishingPositionRange: {
                    loser: [9, 16],
                    winner: [1, 8],
                  },
                },
                {
                  matchUpId: '6bfe3b66-1cbb-4374-9023-a7da114457a7',
                  roundNumber: 2,
                  roundPosition: 4,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [13, 15],
                  finishingRound: 4,
                  finishingPositionRange: {
                    loser: [9, 16],
                    winner: [1, 8],
                  },
                },
                {
                  matchUpId: '01418efc-e243-43aa-9c45-a1b8baa4924f',
                  roundNumber: 2,
                  roundPosition: 5,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [18, 20],
                  finishingRound: 4,
                  finishingPositionRange: {
                    loser: [9, 16],
                    winner: [1, 8],
                  },
                },
                {
                  matchUpId: 'd5f2e49d-ff3d-46d2-b04b-e2970fec6a42',
                  roundNumber: 2,
                  roundPosition: 6,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [24, null],
                  finishingRound: 4,
                  finishingPositionRange: {
                    loser: [9, 16],
                    winner: [1, 8],
                  },
                },
                {
                  matchUpId: 'da519438-5684-4751-8cc9-5eaf89e4bfbb',
                  roundNumber: 2,
                  roundPosition: 7,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [28, null],
                  finishingRound: 4,
                  finishingPositionRange: {
                    loser: [9, 16],
                    winner: [1, 8],
                  },
                },
                {
                  matchUpId: '49b318b0-7789-4fb0-a7c8-8c13a7cf1470',
                  roundNumber: 2,
                  roundPosition: 8,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [30, 32],
                  finishingRound: 4,
                  finishingPositionRange: {
                    loser: [9, 16],
                    winner: [1, 8],
                  },
                },
                {
                  matchUpId: 'a9566537-5041-47ef-bcec-0cc660664319',
                  roundNumber: 3,
                  roundPosition: 1,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [null, null],
                  finishingRound: 3,
                  finishingPositionRange: {
                    loser: [5, 8],
                    winner: [1, 4],
                  },
                },
                {
                  matchUpId: '3b3e43c1-e20c-4aa9-b59e-28732db401cd',
                  roundNumber: 3,
                  roundPosition: 2,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [null, null],
                  finishingRound: 3,
                  finishingPositionRange: {
                    loser: [5, 8],
                    winner: [1, 4],
                  },
                },
                {
                  matchUpId: '749f7d04-c1a4-4ea8-aa5b-5e392fb8e786',
                  roundNumber: 3,
                  roundPosition: 3,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [null, null],
                  finishingRound: 3,
                  finishingPositionRange: {
                    loser: [5, 8],
                    winner: [1, 4],
                  },
                },
                {
                  matchUpId: '06cc75bc-e77c-4a49-823f-44148167c09d',
                  roundNumber: 3,
                  roundPosition: 4,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [null, null],
                  finishingRound: 3,
                  finishingPositionRange: {
                    loser: [5, 8],
                    winner: [1, 4],
                  },
                },
                {
                  matchUpId: '59c6cba4-9cc8-4377-ad2c-bfa5add437db',
                  roundNumber: 4,
                  roundPosition: 1,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [null, null],
                  finishingRound: 2,
                  finishingPositionRange: {
                    loser: [3, 4],
                    winner: [1, 2],
                  },
                },
                {
                  matchUpId: '17eaaf17-5b10-45e2-b1d8-6b8ce864a11a',
                  roundNumber: 4,
                  roundPosition: 2,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [null, null],
                  finishingRound: 2,
                  finishingPositionRange: {
                    loser: [3, 4],
                    winner: [1, 2],
                  },
                },
                {
                  matchUpId: '908665de-0211-4045-8120-eeda8b95965a',
                  roundNumber: 5,
                  roundPosition: 1,
                  matchUpStatus: 'TO_BE_PLAYED',
                  drawPositions: [null, null],
                  finishingRound: 1,
                  finishingPositionRange: {
                    loser: [2, 2],
                    winner: [1, 1],
                  },
                },
              ],
              positionAssignments: [
                {
                  drawPosition: 1,
                  participantId: 'EEC077F9-9F34-40AE-ABBB-6FD680B7EA60',
                },
                {
                  drawPosition: 2,
                  bye: true,
                },
                {
                  drawPosition: 3,
                  participantId: '69D53E88-8921-4135-BE08-7D3955E9D905',
                },
                {
                  drawPosition: 4,
                  participantId: '3DE351D7-3839-4382-9C3E-A362588373BC',
                },
                {
                  drawPosition: 5,
                  participantId: '5036DEBC-230D-4EBE-9C31-41B556E8951C',
                },
                {
                  drawPosition: 6,
                  bye: true,
                },
                {
                  drawPosition: 7,
                  participantId: '1EED4E97-AD8A-4E89-BF11-B2D89E41105D',
                },
                {
                  drawPosition: 8,
                  bye: true,
                },
                {
                  drawPosition: 9,
                  participantId: '3DA2502B-85CC-42F7-902F-5CDDCB29EBB7',
                },
                {
                  drawPosition: 10,
                  bye: true,
                },
                {
                  drawPosition: 11,
                  participantId: 'BD2E3868-36C8-43D1-A06F-D6A953B512B9',
                },
                {
                  drawPosition: 12,
                  participantId: 'ECD2C517-E82B-415F-A689-C7245689274A',
                },
                {
                  drawPosition: 13,
                  participantId: 'DFF8511C-92D3-4B83-8FA6-13CA49AF8B0E',
                },
                {
                  drawPosition: 14,
                  bye: true,
                },
                {
                  drawPosition: 15,
                  participantId: '5BBABB87-11FD-47F6-941E-84AB3A76DEAF',
                },
                {
                  drawPosition: 16,
                  bye: true,
                },
                {
                  drawPosition: 17,
                  bye: true,
                },
                {
                  drawPosition: 18,
                  participantId: 'F553D401-2F62-4AFF-892B-0C189671FC1C',
                },
                {
                  drawPosition: 19,
                  bye: true,
                },
                {
                  drawPosition: 20,
                  participantId: 'D5512670-C0F6-424D-B012-218E9C2B6A01',
                },
                {
                  drawPosition: 21,
                  participantId: 'C8222AA6-13AC-4152-A1E2-929CA0FDA46D',
                },
                {
                  drawPosition: 22,
                  participantId: '1DDC2CD1-CD63-4C43-AA0F-767D77F7F5B7',
                },
                {
                  drawPosition: 23,
                  bye: true,
                },
                {
                  drawPosition: 24,
                  participantId: '6B716DFF-D553-4AC3-B0AF-12BEF8B1F56C',
                },
                {
                  drawPosition: 25,
                  participantId: 'CF68FD6D-B973-4F59-9818-020D05FB3F65',
                },
                {
                  drawPosition: 26,
                  participantId: '95BA08D4-F49B-4F23-A111-48CF09D0D886',
                },
                {
                  drawPosition: 27,
                  bye: true,
                },
                {
                  drawPosition: 28,
                  participantId: 'E293007D-40B5-43F3-B4E3-9FD397A5E3E7',
                },
                {
                  drawPosition: 29,
                  bye: true,
                },
                {
                  drawPosition: 30,
                  participantId: 'DE072B76-F386-48BC-8408-F9301CA8DB88',
                },
                {
                  drawPosition: 31,
                  bye: true,
                },
                {
                  drawPosition: 32,
                  participantId: '38524857-02A0-47C2-8511-A63CCD3EB444',
                },
              ],
              seedLimit: 8,
            },
          ],
          matchUpFormat: 'SET3-S:6/TB7',
          extensions: [
            {
              name: 'appliedPolicies',
              value: {
                seeding: {
                  policyName: 'USTA',
                  duplicateSeedNumbers: true,
                  validSeedPositions: {
                    ignore: true,
                  },
                  seedsCountThresholds: [
                    {
                      drawSize: 4,
                      minimumParticipantCount: 3,
                      seedsCount: 2,
                    },
                    {
                      drawSize: 8,
                      minimumParticipantCount: 5,
                      seedsCount: 2,
                    },
                    {
                      drawSize: 16,
                      minimumParticipantCount: 9,
                      seedsCount: 4,
                    },
                    {
                      drawSize: 32,
                      minimumParticipantCount: 17,
                      seedsCount: 8,
                    },
                    {
                      drawSize: 64,
                      minimumParticipantCount: 33,
                      seedsCount: 16,
                    },
                    {
                      drawSize: 128,
                      minimumParticipantCount: 65,
                      seedsCount: 16,
                    },
                    {
                      drawSize: 128,
                      minimumParticipantCount: 97,
                      seedsCount: 32,
                    },
                  ],
                  seedBlocks: {
                    '1': [['1', '0']],
                    '2': [['0', '1']],
                    '3': [
                      ['1', '.250'],
                      ['0', '.750'],
                    ],
                    '5': [
                      ['1', '.125'],
                      ['1', '.375'],
                      ['0', '.625'],
                      ['0', '.875'],
                    ],
                    '9': [
                      ['1', '.0625'],
                      ['1', '.1875'],
                      ['1', '.3125'],
                      ['1', '.4375'],
                      ['0', '.5625'],
                      ['0', '.6875'],
                      ['0', '.8125'],
                      ['0', '.9375'],
                    ],
                    '17': [
                      ['1', '.03125'],
                      ['1', '.09375'],
                      ['1', '.15625'],
                      ['1', '.21875'],
                      ['1', '.28125'],
                      ['1', '.34375'],
                      ['1', '.40625'],
                      ['1', '.46875'],
                      ['0', '.53125'],
                      ['0', '.59375'],
                      ['0', '.65625'],
                      ['0', '.71875'],
                      ['0', '.78125'],
                      ['0', '.84375'],
                      ['0', '.90625'],
                      ['0', '.96875'],
                    ],
                    '33': [
                      ['1', '0.015625'],
                      ['1', '0.046875'],
                      ['1', '0.078125'],
                      ['1', '0.109375'],
                      ['1', '0.140625'],
                      ['1', '0.171875'],
                      ['1', '0.203125'],
                      ['1', '0.234375'],
                      ['1', '0.265625'],
                      ['1', '0.296875'],
                      ['1', '0.328125'],
                      ['1', '0.359375'],
                      ['1', '0.390625'],
                      ['1', '0.421875'],
                      ['1', '0.453125'],
                      ['1', '0.484375'],
                      ['0', '0.515625'],
                      ['0', '0.546875'],
                      ['0', '0.578125'],
                      ['0', '0.609375'],
                      ['0', '0.640625'],
                      ['0', '0.671875'],
                      ['0', '0.703125'],
                      ['0', '0.734375'],
                      ['0', '0.765625'],
                      ['0', '0.796875'],
                      ['0', '0.828125'],
                      ['0', '0.859375'],
                      ['0', '0.890625'],
                      ['0', '0.921875'],
                      ['0', '0.953125'],
                      ['0', '0.984375'],
                    ],
                    '49': [],
                  },
                },
              },
            },
          ],
        },
      },
    },
  ],
};
